format = "$directory$username$hostname$character"
right_format = "$custom$all$time"

# Disable Git in favour of Jujutsu
git_branch.disabled = true
git_commit.disabled = true
git_state.disabled = true
git_status.disabled = true

add_newline = false

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R"
style = "italic dimmed white"

[directory]
truncation_length = 5
fish_style_pwd_dir_length = 1
truncation_symbol = "…/"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--jj-symbol", "󱗆 ", "--git-symbol", "󰊢 "]
format = "$output "
