#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = [workspace 1 silent] $browser
#exec-once = [workspace 2 silent] $store
exec-once = nm-applet
exec-once = sleep 4 && pkill fcitx5
exec-once = sleep 8 && fcitx5 -d -r
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- hyprsunset -t 5000
# colorshell logout button UI doesn't kill hypr services. So when login it causes infinite loop of systemd trying to restart these services.
# Only failed when logout and login
#exec-once = colorshell
