# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/my-programs.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/autostart.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/keybindings.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/windows-workspaces.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/general-decoration.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/animations.conf
source = ~/.config/nixos/home/dotfiles/dot-config/hypr/layout.conf

################
### MONITORS ###
################
monitor=,preferred,auto,auto

# See https://wiki.hyprland.org/Configuring/Monitors/

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = GDK_SCALE,$scaling
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow




#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    kb_options = grp:win_space_toggle

    # Don't change window focus when moving mouse
    follow_mouse = 1
    follow_mouse_threshold = 1000
    float_switch_override_focus = 0

    sensitivity = 1
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.3
        drag_3fg = 1 # Three finger drag
    }
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

cursor {
    inactive_timeout = 1
}




