
# See https://wiki.hypr.land/Configuring/Scrolling-Layout/#layout-messages
scrolling {
    # the default width of a column
    column_width = 0.91
    direction = left
    follow_focus = true; #when a window is focused, should the layout move to bring it into view automatically
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    focus_on_activate = true
    on_focus_under_fullscreen = 1 # was new_window_takes_over_fullscreen
}
