###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$browser = firefox
$editor = nano
$store = steam
$menu = wofi --show drun
