##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Brave's notification windows have no class or title
windowrule = match:class ^$,match:title ^$,match:float yes # was float,class:^$,title:^$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .* # was suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = no_focus 1,match:class ^$,match:title ^$,match:xwayland 1, match:float 1, match:fullscreen 0,match:pin 0

# fcitx windows rule
windowrule = pseudo on, match:class fcitx

# Make caelestia widgets blurred
#layerrule = no_anim on,         match:namespace caelestia-(launcher|osd|notifications|border-exclusion|area-picker) #was noanim, caelestia-(launcher|osd|notifications|border-exclusion|area-picker)
#layerrule = animation fade,     match:namespace caelestia-(drawers|background)
#layerrule = order 1,            match:namespace caelestia-border-exclusion
#layerrule = order 2,            match:namespace caelestia-bar
#layerrule = xray 1,             match:namespace caelestia-(border|launcher|bar|sidebar|navbar|mediadisplay|screencorners)
#layerrule = blur on,            match:namespace caelestia-.*
#layerrule = blur on,            match:namespace qs-.*
#layerrule = blur_popups on,     match:namespace caelestia-.*
#layerrule = ignore_alpha 0.57,  match:namespace caelestia-.*

# Waybar persistent
workspace = 1, monitor:HDMI-A-2, persistent:true
workspace = 2, monitor:HDMI-A-2, persistent:true
workspace = 3, monitor:HDMI-A-2, persistent:true
workspace = 4, monitor:HDMI-A-2, persistent:true
workspace = 5, monitor:HDMI-A-2, persistent:true

